### PR TITLE
Added 3 new components Badge, Link and Snackbar

### PR DESCRIPTION
**Pull request by Reinier1982**
3 New Components Badge, Link and Snackbar
All official Material UI components 

Badge for showing the number of items on an icon or button.
Link for making an icon or any other component linkable.
Snackbar for making alerts and other messages show in a small pop-up (snackbar).

### CODE REVIEW

**Comment by chrisobdam** [comment]
Why do you have a link component?

**Comment by chrisobdam** [comment]
Maybe better to create a PR per component?

**Comment by Reinier1982** [comment]
> Why do you have a link component?

The Link component is so that you can let the Icon Component become a clickable component. But also so other components like images can be come clickable.

**Comment by nulian** [comment]
Please don't skip the commit hooks
See: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

We use it to generate changelogs at least one commit with feat: added component
would be nice to have.

**Pull request closed without merging**
